name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
  # workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Create key.js file
        run: echo '${{ secrets.FIREBASE }}' > key.js

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: .
          node-version: 20
          package-manager: pnpm@8.9.0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
